services:
  - type: web
    name: ci-farbanalyse-api
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
